name: Specs

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Ruby
      uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.7
    - name: Install graphviz
      run: apt-get install graphviz
    - name: Install
      run: bundle install
    - name: Run specs
      run: bundle exec rspec
