require 'seafoam/version'
require 'seafoam/colors'
require 'seafoam/io_binary_reader'
require 'seafoam/string_unpack_binary_reader'
require 'seafoam/ffi_binary_reader' if defined?(FFI)
require 'seafoam/binary_reader'
require 'seafoam/bgv_parser'
require 'seafoam/graph'
require 'seafoam/annotators'
require 'seafoam/annotators/graal'
require 'seafoam/annotators/fallback'
require 'seafoam/spotlight'
require 'seafoam/graphviz_writer'
require 'seafoam/config'
require 'seafoam/commands'
